books/urls.py
from django.urls import path, include

import books
from books.views import landing_page, books_list, book_detail, book_create, book_edit, book_delete

app_name = 'books'

books_patterns = [
    path('', books_list, name='list'),
    path('create/', book_create, name='create'),
    path('<int:pk>/', include([
        path('edit/', book_edit, name='edit'),
        path('delete/', book_delete, name='delete'),
    ])),
    path('<slug:slug>/', book_detail, name='details'),
]

urlpatterns = [
    path('', landing_page, name='home'),

    path('books/', include(books_patterns)),

]

exercise_templates/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from exercise_templates import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('reviews/', include('reviews.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    # try cloudinary
    # S3 buckets - not free

reviews/urls.py
from django.urls import path, include

from reviews.views import recent_reviews, review_details, review_create, review_delete, review_edit, review_bulk_update

app_name = 'reviews'

reviews_patterns = [
    path('recent/', recent_reviews, name='recent'),
    path('<int:pk>/', review_details, name='details'),
    path('', recent_reviews, name='list'),
    path('create/', review_create, name='create'),
    path('<slug:book_slug>/', review_bulk_update, name='bulk-update'),
    path('<int:pk>/', include([
        path('', review_details, name='details'),
        path('edit/', review_edit, name='edit'),
        path('delete/', review_delete, name='delete'),
    ]))
]

urlpatterns = [
    path('', include(reviews_patterns)),
]

books/models.py
from django.db import models
from django.utils.text import slugify

from books.validators import range_validator2, RangeValidator
from common.models import TimeStampModel


# Create your models here.

class Book(TimeStampModel):
    class GenreChoices(models.TextChoices):
        FICTION = 'Fiction', 'Fiction'
        NONFICTION = 'Non-Fiction', 'Non-Fiction'
        FANTASY = 'Fantasy', 'Fantasy'
        SCIENCE = 'Science', 'Science'
        HISTORY = 'History', 'History'
        MYSTERY = 'Mystery', 'Mystery'

    title = models.CharField(max_length=100, unique=True)
    price = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        validators=[
            RangeValidator(0, 1000, 'Price should be in the range 0-1000')
            ],
        )
    isbn = models.CharField(max_length=12, unique=True)
    cover_image = models.ImageField(null=True, blank=True)
    genre = models.CharField(max_length=50, choices=GenreChoices.choices)
    publishing_date = models.DateField()
    description = models.TextField()
    image_url = models.URLField()
    slug = models.SlugField(
        max_length=100,
        unique=True,
        blank=True, #for our slug on save to allow user to not fill
    )
    pages = models.PositiveIntegerField(null=True, blank=True)
    publisher = models.CharField(max_length=100)
    tags = models.ManyToManyField('Tag')

    #logic for slug we do on saving
    def save(self, *args, **kwargs) -> None:
        if not self.slug:
            self.slug = slugify(f'{self.title}-{self.publisher}')

        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    # def __repr__(self):
    #     return self.title


class Tag(models.Model):
    name = models.CharField(max_length=50)
    books = models.ManyToManyField(Book)

    def __repr__(self):
        return self.name

    def __str__(self):
        return self.name

books/forms.py
from datetime import date
from typing import Any

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from django.core.exceptions import ValidationError

from books.models import Book, Tag
from common.mixins import DisableFormFieldsMixin


# class BookFormBasic(forms.Form):
#     title = forms.CharField(
#         max_length=100,
#         widget=forms.TextInput(attrs={'placeholder': 'e.g. Done'}) #the way we visualize the field
#     ) # label shows by default as the name of the field
#
#     price = forms.DecimalField(
#         max_digits=6,
#         decimal_places=2,
#         min_value=0,
#         widget=forms.NumberInput(attrs={'step': '0.1'}),
#         label='Price (USD)',
#     )
#
#     isbn = forms.CharField(max_length=12, min_length=10,)
#
#     genre = forms.ChoiceField(
#         choices=Book.GenreChoices.choices,
#         #widget=forms.RadioSelect # changes the choice select with radio choices
#     )
#
#     publishing_date = forms.DateField(
#         initial=date.today() # loads with this initial value inserted
#     )
#
#     description = forms.CharField(
#         widget=forms.Textarea()
#     )
#
#     image_url = forms.URLField()
#
#     publisher = forms.CharField(max_length=100)


class BookFormBasic(forms.ModelForm):
    tags = forms.CheckboxSelectMultiple()

    field_order = [
        'title',
        'pages',
        'price',
    ]

    class Meta:
        exclude = ['slug',]
        model = Book

        error_messages = {
            'title': {
                'max_length': 'Title is way too long.',
                'required': 'Please enter the title.',
            },
        }

    #For 1 field
    def clean_isbn(self) -> None: # we dont need value here next to the self, we take the needed value like this
        #Validators start before the clean method, bcs validators are for logical validations on the fields for users
        #Clean methods are for business logic validations
        if self.cleaned_data['isbn'].startswith('978'):
            raise ValidationError('ISBN cannot start with 978')

    #For more fields
    def clean(self) -> dict:
        cleaned = super().clean()

        genre = cleaned.get('genre')
        pages = cleaned.get('pages')

        if pages < 10 and genre == Book.GenreChoices.FICTION:
            raise ValidationError(f'Book of type {Book.GenreChoices.FICTION} cannot be less than 10 pages')
        return cleaned

    def save(self, commit = True):
        if self.publisher:
            self.publisher = self.publisher.capitalize()

        if commit:
            self.instance.save()
        return self.instance

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.fields['tags'].queryset = Tag.objects.all()
        self.helper = FormHelper()
        self.helper.form_id = 'id-exampleForm'
        self.helper.form_class = 'blueForms'
        self.helper.form_method = 'post'
        self.helper.form_action = 'submit_survey'

        self.helper.add_input(Submit('submit', 'Submit'))


class BookCreateForm(BookFormBasic):
    class Meta(BookFormBasic.Meta):
        help_texts = {
            'isbn': 'International Standard Book Number',
        }


class BookEditForm(BookFormBasic):
    pass


class BookDeleteForm(DisableFormFieldsMixin, BookFormBasic):
    class Meta(BookFormBasic.Meta):
    #     widgets = {
    #         'title': forms.TextInput(attrs={'disabled': True}),
    #     }
        labels = {
            'title': 'Book title',
        }


class BookSearchForm(forms.Form): # forms.Form because it is not connected to a model
    query = forms.CharField(max_length=100, label='', required=False)

books/views.py
from django.db.models import Avg, Q
from django.forms import modelform_factory
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

from books.forms import BookFormBasic, BookEditForm, BookDeleteForm, BookCreateForm, BookSearchForm
from books.models import Book


# Create your views here.

def landing_page(request: HttpRequest) -> HttpResponse:
    total_books = Book.objects.all().count()
    latest_book = Book.objects.order_by('-publishing_date').first()

    context = {
        'total_books': total_books,
        'latest_book': latest_book,
        'page_title': 'Home',
    }

    return render(request, 'books/landing_page.html', context)

def books_list(request: HttpRequest) -> HttpResponse:
    search_form = BookSearchForm(request.GET or None)

    list_books = Book.objects.annotate(avg_rating=Avg('reviews__rating')
        ).order_by('title')

    if 'query' in request.GET: # if there is something in this dict
        if search_form.is_valid():
            list_books = list_books.filter(Q(title__icontains=search_form.cleaned_data['query']) |
                                           Q(description__icontains=search_form.cleaned_data['query']))

    context = {
        'books': list_books,
        'page_title': 'Dashboard',
        'search_form': search_form,
    }
    return render(request, 'books/list.html', context)

def book_detail(request: HttpRequest, slug: str) -> HttpResponse:
    book = get_object_or_404(
        Book.objects.annotate(avg_rating=Avg('reviews__rating')),
        slug=slug,
    )

    context = {
        'book': book,
        'page_title': f'{book.title} details',
    }

    return render(request, 'books/detail.html', context)

def book_create(request: HttpRequest) -> HttpResponse:
    if request.user.is_staff:
        BookForm = modelform_factory(Book,fields='__all__',)
    else:
        BookForm = modelform_factory(Book,exclude=('slug',))

    form = BookForm(request.POST or None, request.FILES or None)

    if request.method == 'POST':
        if form.is_valid():
            # Book.objects.create( # this method for forms.Form
            #     **form.cleaned_data, # unpack and fill the form fields from the cleaned data
            # )
            form.save() # this method for forms.ModelForm; we dont need to create an instance

            return redirect('books:home')

    context = {
        'form': form,
    }
    return render(request, 'books/create.html', context)

def book_edit(request: HttpRequest, pk: int) -> HttpResponse:
    book = Book.objects.get(pk=pk)
    form = BookEditForm(request.POST or None, instance=book)
    #instance is only for ModelForms; thats how we change that exact instance of a book

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('books:home')

    context = {
        'form': form,
    }
    return render(request, 'books/edit.html', context)

def book_delete(request: HttpRequest, pk: int) -> HttpResponse:
    book = Book.objects.get(pk=pk)
    form = BookDeleteForm(request.POST or None, instance=book)
    #instance is only for ModelForms; thats how we change that exact instance of a book

    if request.method == 'POST':
        if form.is_valid():
            book.delete() #form doesnt have delete method, so we take the instance and delete it
            return redirect('books:home')

    context = {
        'form': form,
    }
    return render(request, 'books/delete.html', context)

templates/books/create.html
{% extends 'common/base.html' %}

{% block content %}
    <div class="container">
        <h1 class="mt-4">Create Book</h1>
        <form method="post" class="mt-4" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.errors }}
            {% for field in form %}
                <div class="form-group mb-4">
                    {{ field.label_tag }}
                    {{ field }}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>
{% endblock %}

templates/books/delete.html
{% extends 'common/base.html' %}

{% block content %}
    <div class="container">
        <h1 class="mt-4">Delete Book</h1>
        <form method="post" class="mt-4">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group mb-4">
                    {{ field.label_tag }}
                    {{ field }}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
    </div>
{% endblock %}

templates/books/detail.html
{% extends 'common/base.html' %}

{% block title %}{{ page_title }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <img src="{{ book.image_url }}" class="img-fluid" alt="{{ book.title }}">
                <img src="{{ book.cover_image.url }}">
            </div>
            <div class="col-md-8">
                <h1>{{ book.title }}</h1>
                <p><strong>Genre:</strong>{{ book.genre }}</p>
                <p><strong>Publisher:</strong>{{ book.publisher|capfirst }}</p>
                <p><strong>Publishing Date</strong>{{ book.publishing_date }}</p>
                <p><strong>Pages:</strong>{{ book.pages }}</p>
                <p><strong>ISBN:</strong>{{ book.isbn }}</p>
                <p><strong>Price:</strong>{{ book.price }}</p>
                <p><strong>Tags:</strong> {{ book.tags.all|join:', ' }}</p>

                {% if book.avg_rating %}
                    <p><strong>Average Rating:</strong>{{ book.avg_rating|floatformat:2 }}</p>
                {% else %}
                    <p><strong>Average Rating:</strong>No ratings yet.</p>
                {% endif %}
                <p>{{ book.description }}</p>
            </div>
            <div class="col-md-4">
                <a href="{% url 'books:edit' book.pk %}" class="btn btn-warning">Edit</a>
                <a href="{% url 'books:delete' book.pk %}" class="btn btn-danger">Delete</a>
            </div>
        </div>

    <hr class="my-4">

    <h2>Reviews</h2>
    <div class="row">
        {% for review in book.reviews.all %}
        <div class="col-md-6 mb-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Rating: {{ review.rating|floatformat:2 }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">by {{ review.author }}</h6>
                    <p class="card-text">{{ review.body }}</p>
                    
                    {% if review.is_spoler %}
                        <p class="text-danger">This review contains spoilers.</p>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    </div>
{% endblock %}

templates/books/edit.html
{% extends 'common/base.html' %}
{% load crispy_forms_tags %}
{% crispy example_form example_form.helper %}

{% block content %}
    <div class="container">
        <h1 class="mt-4">Edit Book</h1>
            {% crispy form %}
    </div>
{% endblock %}

templates/books/landing_page.html
{% extends 'common/base.html' %}

{% block title %}{{ page_title }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="p-5 mb-4 bg-light rounded-3">
            <div class="container-fluid py-5">
                <h1 class="display-5 fw-bold">Welcome to Book Hub</h1>
                <p class="col-md-8 fs-4">Your one-stop place for book reviews and information.</p>
                <p>We have a total of {{ total_books|default:0 }} books in our collection.</p>
            </div>
        </div>

    {% if latest_book %}
        <div class="row align-items-md-stretch">
            <div class="col-md-12">
                <div class="h-100 p-5 text-white bg-dark rounded-3">
                    <h2>Our Latest Addition</h2>
                    <h3>{{ latest_book.title|upper }}</h3>
                    <p>{{ latest_book.description|lower|capfirst|truncatewords:3|default:'No description.' }}</p>
                    <a href="{% url 'books:details' latest_book.slug %}" class="btn btn-ourline-ligth" type="button">View Details</a>
                </div>
            </div>
        </div>
    {% endif %}
    </div>
{% endblock %}

templates/books/list.html
{% extends 'common/base.html' %}

{% block title %}{{ page_title }}{% endblock %}

{% block content %}
<div class="container">
    <h1 class="mb-4">{{ page_title }}</h1>
    <a href="{% url 'reviews:create' %}" class="btn btn-success mb-3">Add Review</a>
    <div class="row">
        <form>
            {{ search_form }}
            <button>Search</button>
        </form>
        {% for b in books %}
            <div class="col-md-4 mb-4">
                <div class="card">
                    <img src="{{ b.image_url }}" class="card-img-top" alt="{{ b.title }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ b.title }}</h5>
                        <p class="card-text"><strong>Genre:</strong>{{ b.genre }}</p>
                        <p class="card-text"><strong>Price:</strong>${{ b.price }}</p>
                        
                        {% if b.avg_rating %}
                            <p class="card-text"><strong>Average Rating:</strong>{{ b.avg_rating|floatformat:2 }}</p>
                        {% else %}
                            <p class="card-text"><strong>Average Rating:</strong>No ratings yet.</p>
                        {% endif %}
                            
                        <a href="{% url 'books:details' b.slug %}" class="btn btn-primary">View Details</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>    
{% endblock %}