books/urls.py
from django.urls import path, include

import books
from books.views import landing_page, books_list, book_detail, book_create, book_edit, book_delete

app_name = 'books'

books_patterns = [
    path('', books_list, name='list'),
    path('create/', book_create, name='create'),
    path('<int:pk>/', include([
        path('edit/', book_edit, name='edit'),
        path('delete/', book_delete, name='delete'),
    ])),
    path('<slug:slug>/', book_detail, name='details'),
]

urlpatterns = [
    path('', landing_page, name='home'),

    path('books/', include(books_patterns)),

]

exercise_templates/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from exercise_templates import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('reviews/', include('reviews.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    # try cloudinary
    # S3 buckets - not free

reviews/urls.py
from django.urls import path, include

from reviews.views import recent_reviews, review_details, review_create, review_delete, review_edit, review_bulk_update

app_name = 'reviews'

reviews_patterns = [
    path('recent/', recent_reviews, name='recent'),
    path('<int:pk>/', review_details, name='details'),
    path('', recent_reviews, name='list'),
    path('create/', review_create, name='create'),
    path('<slug:book_slug>/', review_bulk_update, name='bulk-update'),
    path('<int:pk>/', include([
        path('', review_details, name='details'),
        path('edit/', review_edit, name='edit'),
        path('delete/', review_delete, name='delete'),
    ]))
]

urlpatterns = [
    path('', include(reviews_patterns)),
]

reviews/models.py
from django.db import models

from common.models import TimeStampModel


# Create your models here.

class Review(TimeStampModel):
    author = models.CharField(max_length=100)
    body = models.TextField()
    rating = models.DecimalField(max_digits=4, decimal_places=2)
    book = models.ForeignKey(
        'books.Book',
        on_delete=models.CASCADE,
        related_name='reviews',)
    is_spoiler = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created_at',)

reviews/forms.py
from typing import Any

from django import forms

from common.mixins import DisableFormFieldsMixin
from reviews.models import Review


class ReviewFormBasic(forms.ModelForm):
    class Meta:
        model = Review
        fields = '__all__'


class ReviewCreateForm(ReviewFormBasic):
    pass


class ReviewEditForm(ReviewFormBasic):
    pass


class ReviewDeleteForm(DisableFormFieldsMixin, ReviewFormBasic):
    pass

reviews/views.py
from django.forms import modelformset_factory
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

from books.models import Book
from reviews.forms import ReviewCreateForm, ReviewEditForm, ReviewDeleteForm
from reviews.models import Review


# Create your views here.

def recent_reviews(request: HttpRequest) -> HttpResponse:
    DEFAULT_REVIEWS_COUNT = 5
    reviews_count = int(request.GET.get('count', DEFAULT_REVIEWS_COUNT))
    # from get request take query parameter(?count=5) else default

    reviews = Review.objects.select_related('book')[:reviews_count]

    context = {
        'reviews': reviews,
        'page_title': 'Recent Reviews',
    }

    return render(request, 'reviews/list.html', context)

def review_details(request: HttpRequest, pk: int) -> HttpResponse:
    review = get_object_or_404(
        Review.objects.select_related('book'),
        pk=pk)

    context = {
        'review': review,
        'page_title': f'{review.author}\'s review on {review.book.title}',
    }
    return render(request, 'reviews/detail.html', context)

def review_create(request: HttpRequest) -> HttpResponse:
    form = ReviewCreateForm(request.POST or None)

    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('reviews:list')

    context = {
        'form': form,
    }

    return render(request, 'reviews/create.html', context)

def review_bulk_update(request: HttpRequest, book_slug: str) -> HttpResponse:
    book = get_object_or_404(Book, slug=book_slug) #We take our book
    ReviewFormSet = modelformset_factory(
        Review,
        form=ReviewEditForm, # This is our form
        can_delete=True, # The form can delete records/gives us a delete check
        extra=1, # 1 additional empty form
    )
    formset = ReviewFormSet(
        request.POST or None,
        queryset=Review.objects.filter(book=book), #the queryset that it should fill with
    )

    if request.method == 'POST' and formset.is_valid():
        instances = formset.save(commit=False) # all objects / queryset of all objects of the forms
        for ins in instances:
            ins.book = book
            ins.save()
        for ins in formset.deleted_objects:
            ins.delete()

        return redirect('reviews:list')

    context = {
        'book': book,
        'formset': formset,
    }

    return render(request, 'reviews/formset_edit.html', context)


def review_edit(request: HttpRequest, pk: int) -> HttpResponse:
    review = get_object_or_404(Review, pk=pk)
    form = ReviewEditForm(request.POST or None, instance=review)

    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('reviews:list')

    context = {
        'form': form,
    }
    return render(request, 'reviews/edit.html', context)

def review_delete(request: HttpRequest, pk: int) -> HttpResponse:
    review = get_object_or_404(Review, pk=pk)
    form = ReviewDeleteForm(request.POST or None, instance=review)

    if request.method == 'POST' and form.is_valid():
        review.delete()
        return redirect('reviews:list')

    context = {
        'form': form,
    }
    return render(request, 'reviews/delete.html', context)

templates/reviews/create.html
{% extends 'common/base.html' %}

{% block content %}
    <div class="container">
        <h1 class="mt-4">Create Review</h1>
        <form method="post" class="mt-4">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group mb-4">
                    {{ field.label_tag }}
                    {{ field }}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>
{% endblock %}

templates/reviews/delete.html
{% extends 'common/base.html' %}

{% block content %}
    <div class="container">
        <h1 class="mt-4">Delete Review</h1>
        <form method="post" class="mt-4">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group mb-4">
                    {{ field.label_tag }}
                    {{ field }}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Delete</button>
        </form>
    </div>
{% endblock %}

templates/reviews/detail.html
{% extends 'common/base.html' %}
{# {% load stars %} #}

{% block title %}{{ page_title }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h1>{{ page_title }}</h1>
            </div>
            <div class="card-body">
                <blockquote class="blockquote mb-0">
                    <p>{{ review.body }}</p>
                    <footer class="blockquote-footer">
                        {{ review.author }}
                        <cite title="Source Title">
                            with a rating of {{ review.rating }}
                        </cite>
                    </footer>
                </blockquote>

                {% if review.is_spoiler %}
                    <p class="text-danger mt-3">This review contains spolers.</p>
                {% endif %}

                <a href="{% url 'books:details' review.book.slug %}" class="btn btn-secondary mt-3">Back to Book Details</a>
                <a href="{% url 'reviews:edit' review.pk %}" class="btn btn-warning mt-3">Edit</a>
                <a href="{% url 'reviews:delete' review.pk %}" class="btn btn-danger mt-3">Delete</a>
            
            </div>
        </div>
    </div>
{% endblock %}

templates/reviews/edit.html
{% extends 'common/base.html' %}

{% block content %}
    <div class="container">
        <h1 class="mt-4">Edit Review</h1>
        <form method="post" class="mt-4">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group mb-4">
                    {{ field.label_tag }}
                    {{ field }}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Edit</button>
        </form>
    </div>
{% endblock %}

templates/reviews/formset_edit.html
{% extends 'common/base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ formset.management_form }}

        {% for form in formset.forms %}
        {{ form }}
            {% if formset.can_delete %}
                <div>
                    {{ form.DELETE }}
                    <label>Delete this review</label>
                </div>
            {% endif %}
        {%  endfor %}

        <button>Save all changes</button>
    </form>
{% endblock %}

templates/reviews/list.html
{% extends 'common/base.html' %}

{% block title %}{{ page_title }}{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="mb-4">{{ page_title }}</h1>
        <div class="row">
            {% for r in reviews %}
            <div class="col-md-6 mb-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">
                            <a href="{% url 'books:details' r.book.slug %}">{{ r.book.title }}</a>
                        </h5>
                        <h6 class="card-subtitle mb-2 text-muted">Rating: {{ r.rating }} by {{ r.author }}</h6>
                        <p class="card-text">{{ r.body }}</p>
                        
                        {% if r.is_spoiler %}
                            <p class="text-danger">This review contains spoilers</p>
                        {% endif %}
                        <a href="{% url 'reviews:details' r.pk %}" class="btn btn-primary">View Review</a>
                    </div>
                </div>
            </div>
        
            {% empty %}
            <div class="col">
                <p>No recent reviews found.</p>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}